INSERT INTO state (id, code, name, country_id) VALUES
(	1	,'AL', 'Alabama', 1),
(	2	,'AK', 'Alaska', 1),
(	3	,'AZ', 'Arizona', 1),
(	4	,'AR', 'Arkansas', 1),
(	5	,'CA', 'California', 1),
(	6	,'CO', 'Colorado', 1),
(	7	,'CT', 'Connecticut', 1),
(	8	,'DE', 'Delaware', 1),
(	9	,'FL', 'Florida', 1),
(	10	,'GA', 'Georgia', 1),
(	11	,'HI', 'Hawaii', 1),
(	12	,'ID', 'Idaho', 1),
(	13	,'IL', 'Illinois', 1),
(	14	,'IN', 'Indiana', 1),
(	15	,'IA', 'Iowa', 1),
(	16	,'KS', 'Kansas', 1),
(	17	,'KY', 'Kentucky', 1),
(	18	,'LA', 'Louisiana', 1),
(	19	,'ME', 'Maine', 1),
(	20	,'MD', 'Maryland', 1),
(	21	,'MA', 'Massachusetts', 1),
(	22	,'MI', 'Michigan', 1),
(	23	,'MN', 'Minnesota', 1),
(	24	,'MS', 'Mississippi', 1),
(	25	,'MO', 'Missouri', 1),
(	26	,'MT', 'Montana', 1),
(	27	,'NE', 'Nebraska', 1),
(	28	,'NV', 'Nevada', 1),
(	29	,'NH', 'New Hampshire', 1),
(	30	,'NJ', 'New Jersey', 1),
(	31	,'NM', 'New Mexico', 1),
(	32	,'NY', 'New York', 1),
(	33	,'NC', 'North Carolina', 1),
(	34	,'ND', 'North Dakota', 1),
(	35	,'OH', 'Ohio', 1),
(	36	,'OK', 'Oklahoma', 1),
(	37	,'OR', 'Oregon', 1),
(	38	,'PA', 'Pennsylvania', 1),
(	39	,'RI', 'Rhode Island', 1),
(	40	,'SC', 'South Carolina', 1),
(	41	,'SD', 'South Dakota', 1),
(	42	,'TN', 'Tennessee', 1),
(	43	,'TX', 'Texas', 1),
(	44	,'UT', 'Utah', 1),
(	45	,'VT', 'Vermont', 1),
(	46	,'VA', 'Virginia', 1),
(	47	,'WA', 'Washington', 1),
(	48	,'WV', 'West Virginia', 1),
(	49	,'WI', 'Wisconsin', 1),
(	50	,'WY', 'Wyoming', 1);
